#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  carbonAccounting:

services:
  chaincode-utilityemissions2:
    container_name: chaincode-utilityemissions2.carbonAccounting.com
    image: krybalko/utilityemissions-chaincode:0.0.4
    environment:
      - CHAINCODE_CCID=
      - CHAINCODE_ADDRESS=0.0.0.0:9999
    ports:
      - "9999:9999"
